### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by ctlee** [LLNL/ddcMD#1]
Are there instructions for building this code? There doesn't appear to be a Makefile specifying dependencies.

Congrats on the the recent manuscript. I'm looking forward to trying ddcMD out.

**Comment by XiaohuaZhangLLNL** [comment]
A brief installation guide has been added to the repo: https://github.com/LLNL/ddcMD/blob/master/INSTALL.md 
In the future CMake will be provided to ease the building process.

**Comment by ctlee** [comment]
Thanks!
