### ISSUE TITLE
Small test files

### ISSUE THREAD

**Issue by oliverdutton** [LLNL/ddcMD#3]
Could you provide test files for a small (~1000 atom) system and the commands that need to be run for it to read in input files/specify a folder?

Thanks,
Oliver

**Comment by XiaohuaZhangLLNL** [comment]
Here is a tiny test case with 6173 martini water particles. Unzip the tar file and run the executable in the directory. All the inputs use default file names. Thus you don't need to specify the inputs.
[tinytestcase.tar.gz](https://github.com/LLNL/ddcMD/files/5613846/tinytestcase.tar.gz)
