### ISSUE TITLE
Restrictions on specific force fields ?

### ISSUE THREAD

**Issue by CharlyEmpereurmot** [LLNL/ddcMD#4]
Hello,

I was wondering why exactly did you (somehow) specify in the paper that this software application is restricted to Martini ? From #3 it seems that users can specify the force field parameters as input. Are their some restrictions in terms of implemented potential functions, for example ? More generally, which parameters of the simulation are NOT accessible to the user and would restrict usage to exclusively Martini ?

I'm looking forward to using this software, great project :+1:

**Comment by XiaohuaZhangLLNL** [comment]
The code is designed not to limit to the Martini force field. It supports multiple force fields. However, for the open source version only the Martini force field is currently supported (mostly due to lack the maintenance efforts on other force fields).
